### ISSUE TITLE
FileNotFoundException on a .NET Standard project

### ISSUE THREAD

**Issue by alexanderkozlenko** [szehetner/InliningAnalyzer#11] opened 2018-11-07 17:43 UTC
Tool exception: `Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.`
Tool output: [inlining_analyzer.log](https://github.com/szehetner/InliningAnalyzer/files/2558544/inlining_analyzer.log)
Tool preffered runtime: `NetCore`
.NET information: [dotnet_info.log](https://github.com/szehetner/InliningAnalyzer/files/2558542/dotnet_info.log)
Project target frameworks: `netstandard1.1+netstandard2.0`
Project source code: https://github.com/alexanderkozlenko/json-rpc

**Comment by szehetner** [comment] 2018-11-07 19:32
I can reproduce the issue. The problem is that for .NET Standard libraries the dependencies are not copied to the output directory and therefore the analyzer can't find them. I'm not yet sure how I can fix this properly though.

In the meantime you can use the following workaround: 
Before running the analyzer, manually copy all missing assemblies (in this case only `Newtonsoft.Json.dll`) into the output folder (`D:\github\json-rpc\bin\Anemonis.JsonRpc\Release\netstandard1.1\`) , then it should work.

**Comment by szehetner** [comment] 2018-11-16 22:32
Version 0.7.4 with a fix for this has been published.

**Closed by szehetner** 2018-11-16 22:32 UTC
